name: platform_file
resolution: workspace
description: An abstraction to allow working with files across multiple platforms.
version: 0.1.1+2
homepage: https://github.com/jiejie-dev/flutter_platform_file

environment:
  sdk: ^3.8.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.15
