# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  chglog:
    cmds:
      - git-chglog -o CHANGELOG.md
    silent: true